services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kleapi
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    expose:
      - 9000
    networks:
      - laravel-network

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root12
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: ege123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx_api
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
       laravel-network:
        aliases:
         - "apisitesi"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kleapi-phpmyadmin-1
    depends_on:
      - db
    environment:
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=ege123
    ports:
      - "8080:80"
    networks:
      - laravel-network

volumes:
  mysql_data:
    driver: local

networks:
  laravel-network:
    driver: bridge
    name: laravel-network