services: 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: klefrontend
    volumes: 
      - ./:/var/www 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx yapılandırma dosyasını bağla 
    expose: 
      - 9000  # PHP-FPM portu 
    networks:
      - laravel-network

  nginx: 
    image: nginx:alpine 
    container_name: nginx_frontend 
    volumes: 
      - ./:/var/www  # Laravel kodlarını bağla 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx yapılandırma dosyasını bağla 
    ports: 
      - "8001:80"  # Nginx portunu 8000'e yönlendir 
    depends_on: 
      - app 
    networks:
      - laravel-network  # doğru ağ tanımlaması yapılmalı

networks:
  laravel-network:
    name: laravel-network
    driver: bridge
